baseURL = "https://tomjagotjarvis.com/"
title = "Tom Jagot-Jarvis"
publishDir = "public"
uglyURLs = false
relativeURLs = true
canonifyURLs = false

[pagination]
  pagerSize = 5

[taxonomies]
  tag = "tags"

[permalinks]
post = "/posts/:slug/"

[minify]
  disableXML = true
