baseURL = "https://tomjagotjarvis.com/"
title = "Tom Jagot-Jarvis"
publishDir = "public"
uglyURLs = false
relativeURLs = true
canonifyURLs = false

pagination.pagerSize = 6

[taxonomies]
  tag = "tags"

[permalinks]
post = "/posts/:slug/"

[minify]
  disableXML = true

[params]
  postImageMax = 1200
  postImageGutter = 24